osqp-eigen: OSQPWrapper::OptimizerData Class Reference
OSQPWrapper::OptimizerData Class Reference
OptimizerData class is a wrapper of the OSQP OSQPData struct.
#include <OptimizerData.hpp>
Public Member Functions
OptimizerData ()
Constructor.
OptimizerData (int n, int m)
Constructor.
~OptimizerData ()
Deconstructor.
void clearHessianMatrix ()
Clear the hessian matrix.
void clearLinearConstraintsMatrix ()
Clear the linear constraints matrix.
void setNumberOfVariables (int n)
Set the number of variables.
void setNumberOfConstraints (int m)
Set the number of constraints.
template<typename T >
bool setHessianMatrix (const Eigen::SparseMatrix< T > &hessianMatrix)
Set the quadratic part of the cost function (Hessian).
template<int n>
bool setGradient (Eigen::Matrix< c_float, n, 1 > &gradientVector)
Set the linear part of the cost function (Gradient).
template<typename T >
bool setLinearConstraintsMatrix (const Eigen::SparseMatrix< T > &linearConstraintsMatrix)
Set the linear constraint matrix A (size m x n)
template<int m>
bool setLowerBound (Eigen::Matrix< c_float, m, 1 > &lowerBoundVector)
Set the array for lower bound (size m).
template<int m>
bool setUpperBound (Eigen::Matrix< c_float, m, 1 > &upperBoundVector)
Set the array for upper bound (size m).
OSQPData *const & getOptimizerData () const
Get the OSQPData struct.
bool isSet () const
Verify if all the matrix and vectors are already set.
Detailed Description
OptimizerData class is a wrapper of the OSQP OSQPData struct.
Definition at line 28 of file OptimizerData.hpp.
Constructor & Destructor Documentation
OSQPWrapper::OptimizerData::OptimizerData (int n, int m)
Constructor.
Parameters
n is the number of variables;
m is the number of constraints.
Definition at line 28 of file OptimizerData.cpp.
References setNumberOfConstraints(), and setNumberOfVariables().
Member Function Documentation
OSQPData *const & OSQPWrapper::OptimizerData::getOptimizerData () const
Get the OSQPData struct.
Returns
a const point to the OSQPData struct.
Definition at line 82 of file OptimizerData.cpp.
bool OSQPWrapper::OptimizerData::isSet () const
Verify if all the matrix and vectors are already set.
Returns
true if all the OSQPData struct are set.
Definition at line 87 of file OptimizerData.cpp.
template<int n> bool OSQPWrapper::OptimizerData::setGradient (Eigen::Matrix< c_float, n, 1 > & gradientVector)
Set the linear part of the cost function (Gradient).
Parameters
gradientVector is the Gradient vector.
Returns
true/false in case of success/failure.
Definition at line 50 of file OptimizerData.tpp.
template<typename T > bool OSQPWrapper::OptimizerData::setHessianMatrix (const Eigen::SparseMatrix< T > & hessianMatrix)
Set the quadratic part of the cost function (Hessian).
It is assumed to be a simmetric matrix.
Parameters
hessianMatrix is the Hessian matrix.
Returns
true/false in case of success/failure.
Definition at line 11 of file OptimizerData.tpp.
References OSQPWrapper::SparseMatrixHelper::createOsqpSparseMatrix().
template<typename T > bool OSQPWrapper::OptimizerData::setLinearConstraintsMatrix (const Eigen::SparseMatrix< T > & linearConstraintsMatrix)
Set the linear constraint matrix A (size m x n)
Parameters
linearConstraintsMatrix is the linear constraints matrix A.
Returns
true/false in case of success/failure.
Definition at line 63 of file OptimizerData.tpp.
References OSQPWrapper::SparseMatrixHelper::createOsqpSparseMatrix().
template<int m> bool OSQPWrapper::OptimizerData::setLowerBound (Eigen::Matrix< c_float, m, 1 > & lowerBoundVector)
Set the array for lower bound (size m).
Parameters
lowerBoundVector is the lower bound constraint.
Returns
true/false in case of success/failure.
Definition at line 109 of file OptimizerData.tpp.
void OSQPWrapper::OptimizerData::setNumberOfConstraints (int m)
Set the number of constraints.
Parameters
m is the number of constraints.
Definition at line 76 of file OptimizerData.cpp.
Referenced by OptimizerData().
void OSQPWrapper::OptimizerData::setNumberOfVariables (int n)
Set the number of variables.
Parameters
n is the number of variables.
Definition at line 70 of file OptimizerData.cpp.
Referenced by OptimizerData().
template<int m> bool OSQPWrapper::OptimizerData::setUpperBound (Eigen::Matrix< c_float, m, 1 > & upperBoundVector)
Set the array for upper bound (size m).
Parameters
upperBoundVector is the upper bound constraint.
Returns
true/false in case of success/failure.
Definition at line 122 of file OptimizerData.tpp.
The documentation for this class was generated from the following files:
OptimizerData.hpp
OptimizerData.cpp
OptimizerData.tpp