osqp-eigen: OSQPWrapper::SparseMatrixHelper Namespace Reference
OSQPWrapper::SparseMatrixHelper Namespace Reference
SparseMatrixHelper namespace is a namspace that contains helper function to handle osqp matrix.
Functions
template<typename T >
bool createOsqpSparseMatrix (const Eigen::SparseMatrix< T > &eigenSparseMatrix, csc *&osqpSparseMatrix)
Allocate an osqpSparseMatrix struct.
template<typename T >
bool osqpSparseMatrixToEigenSparseMatrix (const csc *const &osqpSparseMatrix, Eigen::SparseMatrix< T > &eigenSparseMatrix)
Convert an osqp sparse matrix into an eigen sparse matrix.
template<typename T >
bool osqpSparseMatrixToTriplets (const csc *const &osqpSparseMatrix, std::vector< Eigen::Triplet< T >> &tripletList)
Convert an osqp sparse matrix into a eigen triplet list.
template<typename T >
bool eigenSparseMatrixToTriplets (const Eigen::SparseMatrix< T > &eigenSparseMatrix, std::vector< Eigen::Triplet< T >> &tripletList)
Convert an eigen sparse matrix into a eigen triplet list.
Detailed Description
SparseMatrixHelper namespace is a namspace that contains helper function to handle osqp matrix.
Use it to create ot update or manage an osqp sparse matrix. osqp sparse matrix in compressed-column or triplet form.
Function Documentation
template<typename T > bool OSQPWrapper::SparseMatrixHelper::createOsqpSparseMatrix (const Eigen::SparseMatrix< T > & eigenSparseMatrix, csc *& osqpSparseMatrix)
Allocate an osqpSparseMatrix struct.
NOTE: c_malloc function is used to allocate memory please call c_free to deallcate memory.
Returns
a const point to the csc struct.
Definition at line 9 of file SparseMatrixHelper.tpp.
Referenced by OSQPWrapper::OptimizerData::setHessianMatrix(), and OSQPWrapper::OptimizerData::setLinearConstraintsMatrix().
template<typename T > bool OSQPWrapper::SparseMatrixHelper::eigenSparseMatrixToTriplets (const Eigen::SparseMatrix< T > & eigenSparseMatrix, std::vector< Eigen::Triplet< T >> & tripletList)
Convert an eigen sparse matrix into a eigen triplet list.
Parameters
eigenSparseMatrix is the eigen sparse matrix object;
tripletList is a std::vector containing the triplet.
Returns
a const point to the csc struct.
Definition at line 139 of file SparseMatrixHelper.tpp.
template<typename T > bool OSQPWrapper::SparseMatrixHelper::osqpSparseMatrixToEigenSparseMatrix (const csc *const & osqpSparseMatrix, Eigen::SparseMatrix< T > & eigenSparseMatrix)
Convert an osqp sparse matrix into an eigen sparse matrix.
Parameters
osqpSparseMatrix is a constant pointer to a constant csc struct;
eigenSparseMatrix is the eigen sparse matrix object.
Returns
a const point to the csc struct.
Definition at line 110 of file SparseMatrixHelper.tpp.
References osqpSparseMatrixToTriplets().
template<typename T > bool OSQPWrapper::SparseMatrixHelper::osqpSparseMatrixToTriplets (const csc *const & osqpSparseMatrix, std::vector< Eigen::Triplet< T >> & tripletList)
Convert an osqp sparse matrix into a eigen triplet list.
Parameters
osqpSparseMatrix is reference to a constant pointer to a constant csc struct;
tripletList is a std::vector containing the triplet.
Returns
a const point to the csc struct.
Definition at line 72 of file SparseMatrixHelper.tpp.
Referenced by osqpSparseMatrixToEigenSparseMatrix().